### ISSUE TITLE
Generation steps for the semi-synthetic dataset

### ISSUE THREAD

**Issue by alwc** [machine-intelligence-laboratory/DDI-100#2]
Hi MIPT team,

I found the quality of the semi-synthetic dataset to be quite good, thanks for the creation! Would you consider open-sourcing the generation code so that others could extend it for different scripts?

**Comment by ghost** [comment]
Unfortunately, we are not able to share the code. But I can answer if you have any questions about the generation pipeline.
Also we posted a preprint. Main dataset features and some experimental results are described.
https://arxiv.org/abs/1912.11658

**Comment by alwc** [comment]
@i-vasiliev I see, that's understandable. I'll come back to you if I have any follow-up questions, thanks!
