### ISSUE TITLE
Download quota exceeded

### ISSUE THREAD

**Issue by SebastienLinker** [machine-intelligence-laboratory/DDI-100#6]
Hi, 

I can't download the dataset because the quota for each of the 33 files has been exceeded. Is it possible for you to reupload it somewhere else or create a torrent? That would be great

Thanks

**Comment by ghost** [comment]
Sorry for late answer. I was not able to reproduce this case and decided that this was a temporary Google Drive issue.
In a short time I am going to update this repository with a new DDI-100 version, so if the problem is still actual feel free to reopen the issue.

**Comment by SebastienLinker** [comment]
Yes it was temporary, I finally managed to download it, thanks
