### ISSUE TITLE
 language in dataset

### ISSUE THREAD

**Issue by Ru-Van** [machine-intelligence-laboratory/DDI-100#7]
What kind of lang (ru, eng) in dataset do you have? If you have Rus data, could you set number of zip file, thanks.

**Comment by Victro1911** [comment]
I know this is way too late, but I checked and the files are like this:
RU:1,3,4,5,9,11,14,17,19,21,22,23,24,26,28,29
EN:2,6,7,8,10,12,13,15,16,18,20,25,27,30,31,32,33

**Comment by ghost** [comment]
@Victro1911 Thanks a lot! Forgot about the issue(
