### ISSUE TITLE
What's the language of the dataset?

### ISSUE THREAD

**Issue by negarsami4** [machine-intelligence-laboratory/DDI-100#8]
Hello! would you mind to tell me what is the language of the pdfs? I downloaded some and all of them were in Russian, is it the fact for all of other ones?

Thanks

**Comment by spairet** [comment]
Both English and Russian books are presented in the dataset. Languages of pdfs are following:
Ru: 1, 3, 4, 5, 9, 11, 14, 17, 19, 21, 22, 23, 24, 26, 28, 29
En: 2, 6, 7, 8, 10, 12, 13, 15, 16, 18, 20, 25, 27, 30, 31, 32, 33

**Comment by negarsami4** [comment]
> Both English and Russian books are presented in the dataset. Languages of pdfs are following:
> Ru: 1, 3, 4, 5, 9, 11, 14, 17, 19, 21, 22, 23, 24, 26, 28, 29
> En: 2, 6, 7, 8, 10, 12, 13, 15, 16, 18, 20, 25, 27, 30, 31, 32, 33

By any chance do you have the whole code of the paper? I could find some of them only on the GitHub.

**Comment by spairet** [comment]
Unfortunately, as was mentioned in #2, we are not able to share the code itself, but I can answer questions about generation pipeline, if you have some.
